# .github/workflows/convert-to-pdf.yml

name: MD to HTML and PDF
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
      - master
    # Paths can be used to only trigger actions when you have edited certain files, such as a file within the /docs directory
    paths:
      - '**.md'

jobs:
  converttopdf:
    name: Build PDF
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_dir: 'README.md'
          output_dir: html
          build_html: True
      - uses: actions/upload-artifact@v1
        with:
          name: uploaddocs
          path: html
