# This is a basic workflow that is manually triggered

name: Create PDF

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push
jobs:
  CreatePDF:
    runs-on: ubuntu-latest
    steps:
    - name: Cache wkthtmltopdf
      uses: actions/cache@v3.3.2
      id: cache-wkhtmltopdf
      with:
        path: "~/wkhtmltox/"
        key: ${{ runner.os }}-wkhtmltopdf-${{ hashFiles('**/*.deb') }}
  
    - name: Download wkthtmltopdf & dependencies
      if: steps.cache-wkhtmltopdf.outputs.cache-hit != 'true'
      run: |
        mkdir ~/wkhtmltox
        wget -O ~/wkhtmltox/wkhtmltox.deb https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6-1/wkhtmltox_0.12.6-1.bionic_amd64.deb
        wget -O ~/wkhtmltox/xfonts-encodings.deb http://archive.ubuntu.com/ubuntu/pool/main/x/xfonts-encodings/xfonts-encodings_1.0.4-2_all.deb
        wget -O ~/wkhtmltox/xfonts-utils.deb http://archive.ubuntu.com/ubuntu/pool/main/x/xfonts-utils/xfonts-utils_7.7+6_amd64.deb
        wget -O ~/wkhtmltox/xfonts-75dpi.deb http://archive.ubuntu.com/ubuntu/pool/universe/x/xfonts-75dpi/xfonts-75dpi_1.0.4+nmu1_all.deb
        wget -O ~/wkhtmltox/xfonts-base.deb http://archive.ubuntu.com/ubuntu/pool/main/x/xfonts-base/xfonts-base_1.0.4+nmu1_all.deb
    - name: Install wkhtmltopdf
      run: |
        sudo dpkg -i ~/wkhtmltox/xfonts-encodings.deb
        sudo dpkg -i ~/wkhtmltox/xfonts-utils.deb
        sudo dpkg -i ~/wkhtmltox/xfonts-75dpi.deb
        sudo dpkg -i ~/wkhtmltox/xfonts-base.deb
        sudo dpkg -i ~/wkhtmltox/wkhtmltox.deb
    - name: Create PDF from GitHub Pages
      run: |
          wkhtmltopdf https://cufe-student-guide.github.io/ ~/CUFE-Student-Guide.pdf
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        title: "CUFE Student Guide PDF"
        files: |
          *.pdf
